### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by qron** [beedeez/react-native-auto-scroll#1]
- [x] Scroll to bottom on mount
- [x] Scroll to bottom when keyboard did show
- [ ] Keep y-offset of all discussions scrollview when entering in discussion and pressing back
- [ ] Set timer on last action to disable scrolling to bottom on new message while user is acting

**Comment by qron** [comment]
- [ ] Scroll to child position method
